version: '3.3'
services:

    nginx:
        image: nginx
        ports:
            - "8088:80"
        depends_on:
            - php
        volumes:
            - .:/app:ro
            - ./dev/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro

    php:
        build: dev/php
        volumes:
            - .:/app:cached
            - ./var:/app/var:delegated
            - ./vendor:/app/vendor:delegated
            - ./public/node_modules:/app/public/node_modules:ro
        depends_on:
            - db


    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - "3366:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
